NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Validator.kyc.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Validator.kyc.com-cert.pem
    OrganizationalUnitIdentifier: peer
