NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Client.kyc.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Client.kyc.com-cert.pem
    OrganizationalUnitIdentifier: peer
